language: python
python:
  - 3.5
before_install:
  - pip install nose
install:
  - python setup.py build
  - python setup.py install
  - python setup.py egg_info
  - pip install -e .
script:
  - python setup.py test
